_target_: pytorch_lightning.trainer.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1 # prevents early stopping

deterministic: False

strategy: ddp

max_epochs: 100

num_sanity_val_steps: 0
overfit_batches: 0
check_val_every_n_epoch: 1
log_every_n_steps: 50
gradient_clip_val: 5.0

accelerator: gpu
devices: 1
num_nodes: 1
sync_batchnorm: True